spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
