spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: userservice
            uri: http://localhost:8080/
            predicates:
              - Path=/**

server:
  port: 8000
